### ISSUE TITLE
Using two number release version creates type error

### ISSUE THREAD

**Issue by btkostner** [elementary/houston#419]
If a project has two number release like `0.5`, then we get a TypeError on dashboard load. This seams to get pass database validation on the GitHub hook.

**Comment by btkostner** [comment]
So I don't have to look at the logs again:
```
 Tue, 25 Apr 2017 23:43:53 GMT houston:server:error TypeError: Invalid Version: null
     at new SemVer (/var/houston/node_modules/semver/semver.js:279:11)
     at SemVer.compare (/var/houston/node_modules/semver/semver.js:342:13)
     at Function.compare (/var/houston/node_modules/semver/semver.js:566:31)
     at /var/houston/build/lib/database/project.js:191:29
     at Array.sort (native)
     at Array.sort (/var/houston/node_modules/core-js/modules/es6.array.sort.js:21:15)
     at Array.sort (/var/houston/node_modules/mongoose/lib/types/array.js:603:23)
     at model.<anonymous> (/var/houston/build/lib/database/project.js:190:32)
     at VirtualType.applyGetters (/var/houston/node_modules/mongoose/lib/virtualtype.js:77:25)
     at model.Document.get (/var/houston/node_modules/mongoose/lib/document.js:956:18)
     at model.get [as release] (/var/houston/node_modules/mongoose/lib/document.js:1784:25)
     at model.schema.methods.getStatus (/var/houston/build/lib/database/project.js:316:14)
     at _callee$ (/var/houston/build/houston/controller/dashboard.js:92:61)
     at tryCatch (/var/houston/node_modules/regenerator-runtime/runtime.js:63:40)
     at GeneratorFunctionPrototype.invoke [as _invoke] (/var/houston/node_modules/regenerator-runtime/runtime.js:337:22)
     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/houston/node_modules/regenerator-runtime/runtime.js:96:21)
     at tryCatch (/var/houston/node_modules/regenerator-runtime/runtime.js:63:40)
     at invoke (/var/houston/node_modules/regenerator-runtime/runtime.js:139:20)
     at /var/houston/node_modules/regenerator-runtime/runtime.js:184:11
     at Promise._execute (/var/houston/node_modules/bluebird/js/release/debuggability.js:299:9)
     at Promise._resolveFromExecutor (/var/houston/node_modules/bluebird/js/release/promise.js:481:18)
     at new Promise (/var/houston/node_modules/bluebird/js/release/promise.js:77:14)
     at callInvokeWithMethodAndArg (/var/houston/node_modules/regenerator-runtime/runtime.js:183:16)
     at AsyncIterator.enqueue (/var/houston/node_modules/regenerator-runtime/runtime.js:206:13)
     at AsyncIterator.prototype.(anonymous function) [as next] (/var/houston/node_modules/regenerator-runtime/runtime.js:96:21)
     at Object.runtime.async (/var/houston/node_modules/regenerator-runtime/runtime.js:226:14)
     at _callee (/var/houston/build/houston/controller/dashboard.js:87:39)
     at tryCatcher (/var/houston/node_modules/bluebird/js/release/util.js:16:23)
     at MappingPromiseArray._promiseFulfilled (/var/houston/node_modules/bluebird/js/release/map.js:61:38)
     at MappingPromiseArray.PromiseArray._iterate (/var/houston/node_modules/bluebird/js/release/promise_array.js:113:31)
     at MappingPromiseArray.init (/var/houston/node_modules/bluebird/js/release/promise_array.js:77:10)
     at MappingPromiseArray._asyncInit (/var/houston/node_modules/bluebird/js/release/map.js:30:10)
     at Async._drainQueue (/var/houston/node_modules/bluebird/js/release/async.js:143:12)
     at Async._drainQueues (/var/houston/node_modules/bluebird/js/release/async.js:148:10)
     at Immediate.Async.drainQueues (/var/houston/node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:666:20)
     at tryOnImmediate (timers.js:639:5)
     at processImmediate [as _immediateCallback] (timers.js:611:5)

```

**Comment by lewisgoddard** [comment]
Consider using [SemVish](https://github.com/megawac/SemVish) before writing to db:

```
clean("1.2") // => 1.2.0
clean("1.2.0") // => 1.2.0
clean("1.2.0-beta1") // => 1.2.0-beta1
clean("1.2.0beta1") // => 1.2.0-beta1
clean("1.2-alpha1") // => 1.2.0-alpha1
clean("1.2alpha1") // => 1.2.0-alpha1
clean("1") // => 1.0.0
clean("1-rc1") // => 1.0.0-rc1
clean("1rc1") // => 1.0.0-rc1
clean("alpha1") // => 0.0.0-alpha1

// Handes prefixs and trims strings for all inputs (pretty much every stupid scheme I've ever seen)
clean("v-1.2.0     ") // => 1.2.0
clean("   v1.2   ") // => 1.2.0
clean("==v==1.2") // => 1.2.0
clean("_v--1.2.0") // => 1.2.0
clean("V1.2") // => 1.2.0
clean("-VERSION-1.2 ") // => 1.2.0
clean("v.1.2") // => 1.2.0
```

**Comment by babluboy** [comment]
I have tried two things on Bookworm for this issue:
1- Updated the existing release tag 0.5 to 0.5.0 and when I logged into Dashboard the same issue is present
2- Created a new release on GH with tag 0.5.1 and same issue when I logged back into Dashboard

Do I need to delete the older releases of o.5 and 0.5.1 to get the AppCenter integration working again?
![screenshot from 2017-04-26 07 36 52](https://cloud.githubusercontent.com/assets/14061478/25421105/33e28404-2a53-11e7-9094-c6fd99c59049.jpeg)

**Comment by babluboy** [comment]
Also, might be worth accommodating the semantics of the release version mention on GH while making a release. i.e.

> 

Tagging suggestions

It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4.

If the tag isn’t meant for production use, add a pre-release version after the version name. Some good pre-release versions might be v0.2-alpha or v5.9-beta.3.

**Comment by btkostner** [comment]
All the version _should_ be ran through the clean and valid function before being entered to the database. It's probably just missing somewhere.
