### ISSUE TITLE
Accept icons from theme, not shipped only

### ISSUE THREAD

**Issue by codygarver** [elementary/houston#590]
```
Error while running build for https://github.com/elementary/appcenter for 0.0.1
workable: Incorrect icon value
  Error: Incorrect icon value
      at DesktopIcon.<anonymous> (/home/travis/build/elementary/appcenter/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:43:23)
      at Generator.next (<anonymous>)
      at fulfilled (/home/travis/build/elementary/appcenter/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:8:58)
      at <anonymous>
```

**Comment by btkostner** [comment]
Just as a note: this is most likely going to be implimented with a new `type: System` that will run different tests for elementary apps vs third party apps.

**Comment by btkostner** [comment]
Should be fixed in https://github.com/elementary/houston/commit/6c57a51e15e7dcebb356c7f612bf0af4a45f1b72. Make sure you run the build with `--type system-app` and it should skip the some tests like RDNN icon test. I have a simple spec test for it, but I wasn't able to test on a real elementary repo because liftoff keeps failing for them.
