### ISSUE TITLE
Fails to build with error about undefined split

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#605]
Videos currently failing to build: https://travis-ci.org/elementary/videos/builds/368944118?utm_source=github_status&utm_medium=notification

```
  Error: Cannot read property 'split' of undefined
      at Worker.report (/home/travis/build/elementary/videos/node_modules/@elementaryos/houston/dest/worker/worker.js:248:25)
      at Worker.<anonymous> (/home/travis/build/elementary/videos/node_modules/@elementaryos/houston/dest/worker/worker.js:179:26)
      at Generator.throw (<anonymous>)
      at rejected (/home/travis/build/elementary/videos/node_modules/@elementaryos/houston/dest/worker/worker.js:11:65)
      at <anonymous>
```

**Comment by babluboy** [comment]
Nutty build also failed with the same error, while the actual Appcenter submission succeeded.
https://travis-ci.org/babluboy/nutty/builds/368852730?utm_source=github_status&utm_medium=notification

**Comment by btkostner** [comment]
Fixed now. You can restart your travis tests.
