### ISSUE TITLE
"Missing shipped binary error" in Houston CI

### ISSUE THREAD

**Issue by Timecraft** [elementary/houston#606]
This may be a duplicate of an issue I already posted. If so, I apologize, I could not see it when looking at the issues I have posted. If not, then I'm questioning what happened. Nonetheless, on with the issue:

Using Houston CI, my project (Notifier) continuously runs into an issue where it is "Missing shipped binary" in both Juno and Loki builds. I've done many tweaks to my code to see if I could fix it to no avail, and this includes changing the executable binary name. There is also the high chance that this could be due to the fact that I am not super-familiar with .travis.yml files (I did do the reading linked on the Medium post). I'm unsure if this is a bug with Houston CI or the more likely scenario where it's something I've borked up in my own code. Here is the CI log (error message is the same on both Juno and Loki builds, with the minor change of the DIST name.):

```
Worker information
hostname: faede0aa-3457-4ca4-acc0-ea3f006799df@1.production-1-worker-org-f-6-gce
version: v3.6.0 https://github.com/travis-ci/worker/tree/170b2a0bb43234479fd1911ba9e4dbcc36dadfad
instance: travis-job-0ba5a4f1-f207-4753-b9db-9d2e5f8b7511 travis-ci-garnet-trusty-1512502259-986baf0 (via amqp)
startup: 26.438781483s
mode of ‘/usr/local/clang-5.0.0/bin’ changed from 0777 (rwxrwxrwx) to 0775 (rwxrwxr-x)
system_info
Build system informationyaml
Build language: node_js
Build group: stable
Build dist: trusty
Build id: 369627237
Job id: 369627239
Runtime kernel version: 4.4.0-101-generic
travis-build version: e0f4abce4
Build image provisioning date and time
Tue Dec  5 19:58:13 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Cookbooks Version
7c2c6a6 https://github.com/travis-ci/travis-cookbooks/tree/7c2c6a6
git version
git version 2.15.1
bash version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
clang version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-5.0.0/bin
jq version
jq-1.5
bats version
Bats 0.4.0
shellcheck version
0.4.6
shfmt version
v2.0.0
ccache version
ccache version 3.1.9
Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2011 Joel Rosdahl
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
cmake version
cmake version 3.9.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
heroku version
heroku-cli/6.14.39-addc925 (linux-x64) node-v9.2.0
imagemagick version
Version: ImageMagick 6.7.7-10 2017-07-31 Q16 http://www.imagemagick.org
md5deep version
4.2
mercurial version
Mercurial Distributed SCM (version 4.2.2)
(see https://mercurial-scm.org for more information)
Copyright (C) 2005-2017 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
mysql version
mysql  Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64) using  EditLine wrapper
openssl version
OpenSSL 1.0.1f 6 Jan 2014
packer version
Packer v1.0.2
Your version of Packer is out of date! The latest version
is 1.1.2. You can update by downloading from www.packer.io
postgresql client version
psql (PostgreSQL) 9.6.6
ragel version
Ragel State Machine Compiler version 6.8 Feb 2013
Copyright (c) 2001-2009 by Adrian Thurston
subversion version
svn, version 1.8.8 (r1568071)
   compiled Aug 10 2017, 17:20:39 on x86_64-pc-linux-gnu
Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/
The following repository access (RA) modules are available:
* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.3
  - handles 'http' scheme
  - handles 'https' scheme
sudo version
Sudo version 1.8.9p5
Configure options: --prefix=/usr -v --with-all-insults --with-pam --with-fqdn --with-logging=syslog --with-logfac=authpriv --with-env-editor --with-editor=/usr/bin/editor --with-timeout=15 --with-password-timeout=0 --with-passprompt=[sudo] password for %p:  --without-lecture --with-tty-tickets --disable-root-mailer --enable-admin-flag --with-sendmail=/usr/sbin/sendmail --with-timedir=/var/lib/sudo --mandir=/usr/share/man --libexecdir=/usr/lib/sudo --with-sssd --with-sssd-lib=/usr/lib/x86_64-linux-gnu --with-selinux
Sudoers policy plugin version 1.8.9p5
Sudoers file grammar version 43
Sudoers path: /etc/sudoers
Authentication methods: 'pam'
Syslog priority to use when user authenticates successfully: notice
Syslog priority to use when user authenticates unsuccessfully: alert
Send mail if the user is not in sudoers
Use a separate timestamp for each user/tty combo
Lecture user the first time they run sudo
Root may run sudo
Allow some information gathering to give useful error messages
Require fully-qualified hostnames in the sudoers file
Visudo will honor the EDITOR environment variable
Set the LOGNAME and USER environment variables
Length at which to wrap log file lines (0 for no wrap): 80
Authentication timestamp timeout: 15.0 minutes
Password prompt timeout: 0.0 minutes
Number of tries to enter a password: 3
Umask to use or 0777 to use user's: 022
Path to mail program: /usr/sbin/sendmail
Flags for mail program: -t
Address to send mail to: root
Subject line for mail messages: *** SECURITY information for %h ***
Incorrect password message: Sorry, try again.
Path to authentication timestamp dir: /var/lib/sudo
Default password prompt: [sudo] password for %p: 
Default user to run commands as: root
Value to override user's $PATH with: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Path to the editor for use by visudo: /usr/bin/editor
When to require a password for 'list' pseudocommand: any
When to require a password for 'verify' pseudocommand: all
File descriptors >= 3 will be closed before executing a command
Environment variables to check for sanity:
	TZ
	TERM
	LINGUAS
	LC_*
	LANGUAGE
	LANG
	COLORTERM
Environment variables to remove:
	RUBYOPT
	RUBYLIB
	PYTHONUSERBASE
	PYTHONINSPECT
	PYTHONPATH
	PYTHONHOME
	TMPPREFIX
	ZDOTDIR
	READNULLCMD
	NULLCMD
	FPATH
	PERL5DB
	PERL5OPT
	PERL5LIB
	PERLLIB
	PERLIO_DEBUG 
	JAVA_TOOL_OPTIONS
	SHELLOPTS
	GLOBIGNORE
	PS4
	BASH_ENV
	ENV
	TERMCAP
	TERMPATH
	TERMINFO_DIRS
	TERMINFO
	_RLD*
	LD_*
	PATH_LOCALE
	NLSPATH
	HOSTALIASES
	RES_OPTIONS
	LOCALDOMAIN
	CDPATH
	IFS
Environment variables to preserve:
	JAVA_HOME
	TRAVIS
	CI
	DEBIAN_FRONTEND
	XAUTHORIZATION
	XAUTHORITY
	PS2
	PS1
	PATH
	LS_COLORS
	KRB5CCNAME
	HOSTNAME
	HOME
	DISPLAY
	COLORS
Locale to use while parsing sudoers: C
Directory in which to store input/output logs: /var/log/sudo-io
File in which to store the input/output log: %{seq}
Add an entry to the utmp/utmpx file when allocating a pty
PAM service name to use
PAM service name to use for login shells
Create a new PAM session for the command to run in
Maximum I/O log sequence number: 0
Local IP address and netmask pairs:
	10.240.0.28/255.255.255.255
	172.17.0.1/255.255.0.0
Sudoers I/O plugin version 1.8.9p5
gzip version
gzip 1.6
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
Written by Jean-loup Gailly.
zip version
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
Currently maintained by E. Gordon.  Please send bug reports to
the authors using the web page at www.info-zip.org; see README for details.
Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip,
as of above date; see http://www.info-zip.org/ for other sites.
Compiled with gcc 4.8.2 for Unix (Linux ELF) on Oct 21 2013.
Zip special compilation options:
	USE_EF_UT_TIME       (store Universal Time)
	BZIP2_SUPPORT        (bzip2 library version 1.0.6, 6-Sept-2010)
	    bzip2 code and library copyright (c) Julian R Seward
	    (See the bzip2 license for terms of use)
	SYMLINK_SUPPORT      (symbolic links supported)
	LARGE_FILE_SUPPORT   (can read and write large files on file system)
	ZIP64_SUPPORT        (use Zip64 to store large files in archives)
	UNICODE_SUPPORT      (store and read UTF-8 Unicode paths)
	STORE_UNIX_UIDs_GIDs (store UID/GID sizes/values using new extra field)
	UIDGID_NOT_16BIT     (old Unix 16-bit UID/GID extra field not used)
	[encryption, version 2.91 of 05 Jan 2007] (modified for Zip 3)
Encryption notice:
	The encryption code of this program is not copyrighted and is
	put in the public domain.  It was originally written in Europe
	and, to the best of our knowledge, can be freely distributed
	in both source and object forms from any country, including
	the USA under License Exception TSU of the U.S. Export
	Administration Regulations (section 740.13(e)) of 6 June 2002.
Zip environment options:
             ZIP:  [none]
          ZIPOPT:  [none]
vim version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
Included patches: 1-52
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions      
iptables version
iptables v1.4.21
curl version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
wget version
GNU Wget 1.15 built on linux-gnu.
rsync version
rsync  version 3.1.0  protocol version 31
gimme version
v1.2.0
nvm version
0.33.6
perlbrew version
/home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.80
phpenv version
rbenv 1.1.1-25-g6aa70b6
rvm version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
default ruby version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
CouchDB version
couchdb 1.6.1
ElasticSearch version
5.5.0
Installed Firefox version
firefox 56.0.2
MongoDB version
MongoDB 3.4.10
PhantomJS version
2.1.1
Pre-installed PostgreSQL versions
9.2.24
9.3.20
9.4.15
9.5.10
9.6.6
RabbitMQ Version
3.6.14
Redis version
redis-server 4.0.6
riak version
2.2.3
Pre-installed Go versions
1.7.4
ant version
Apache Ant(TM) version 1.9.3 compiled on April 8 2014
mvn version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T07:58:13Z)
Maven home: /usr/local/maven-3.5.2
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-98-generic", arch: "amd64", family: "unix"
gradle version
------------------------------------------------------------
Gradle 4.0.1
------------------------------------------------------------
Build time:   2017-07-07 14:02:41 UTC
Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826
Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.4.0-98-generic amd64
lein version
Leiningen 2.8.1 on Java 1.8.0_151 Java HotSpot(TM) 64-Bit Server VM
Pre-installed Node.js versions
v4.8.6
v6.12.0
v6.12.1
v8.9
v8.9.1
phpenv versions
  system
  5.6
* 5.6.32 (set by /home/travis/.phpenv/version)
  7.0
  7.0.25
  7.1
  7.1.11
  hhvm
  hhvm-stable
composer --version
Composer version 1.5.2 2017-09-11 16:59:25
Pre-installed Ruby versions
ruby-2.2.7
ruby-2.3.4
ruby-2.4.1
removed ‘/etc/apt/sources.list.d/basho_riak.list’
Network availability confirmed.
127.0.0.1 localhost nettuno travis vagrant
127.0.1.1 travis-job-0ba5a4f1-f207-4753-b9db-9d2e5f8b7511 travis-job-0ba5a4f1-f207-4753-b9db-9d2e5f8b7511 ip4-loopback trusty64
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release: The following signatures were invalid: KEYEXPIRED 1515625755
W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release' is not signed.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
git.checkout
0.00s$ git clone --depth=50 --branch=master https://github.com/Timecraft/notifier.git Timecraft/notifier
Cloning into 'Timecraft/notifier'...
remote: Counting objects: 280, done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 280 (delta 169), reused 249 (delta 148), pack-reused 0
Receiving objects: 100% (280/280), 173.50 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (169/169), done.
$ cd Timecraft/notifier
$ git checkout -qf dedecfdd143d4cf19844ec9fd8b7415d732dbbf8
apt
Adding APT Sources (BETA)
$ export DEBIAN_FRONTEND=noninteractive
1.67s$ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
gpg: keyring `/tmp/tmp1l7gzkzg/secring.gpg' created
gpg: keyring `/tmp/tmp1l7gzkzg/pubring.gpg' created
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp1l7gzkzg/trustdb.gpg: trustdb created
gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
7.71s$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
22.65s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libstdc++-5-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  gcc-5-base gcc-7-base libasan2 libatomic1 libcilkrts5 libgcc-5-dev libgcc1
  libgomp1 libitm1 liblsan0 libmpx0 libquadmath0 libstdc++6 libtsan0 libubsan0
Suggested packages:
  libstdc++-5-doc
The following NEW packages will be installed:
  gcc-5-base gcc-7-base libasan2 libcilkrts5 libgcc-5-dev liblsan0 libmpx0
  libstdc++-5-dev libubsan0
The following packages will be upgraded:
  libatomic1 libgcc1 libgomp1 libitm1 libquadmath0 libstdc++6 libtsan0
7 upgraded, 9 newly installed, 0 to remove and 178 not upgraded.
Need to get 4,929 kB of archives.
After this operation, 29.1 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 gcc-7-base amd64 7.2.0-1ubuntu1~14.04 [17.6 kB]
Get:2 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libgcc1 amd64 1:7.2.0-1ubuntu1~14.04 [39.4 kB]
Get:3 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libstdc++6 amd64 7.2.0-1ubuntu1~14.04 [305 kB]
Get:4 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 gcc-5-base amd64 5.4.1-2ubuntu1~14.04 [17.0 kB]
Get:5 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libasan2 amd64 5.4.1-2ubuntu1~14.04 [261 kB]
Get:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libatomic1 amd64 7.2.0-1ubuntu1~14.04 [9,012 B]
Get:7 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libcilkrts5 amd64 7.2.0-1ubuntu1~14.04 [42.2 kB]
Get:8 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libgomp1 amd64 7.2.0-1ubuntu1~14.04 [75.8 kB]
Get:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libitm1 amd64 7.2.0-1ubuntu1~14.04 [27.5 kB]
Get:10 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 liblsan0 amd64 7.2.0-1ubuntu1~14.04 [125 kB]
Get:11 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libmpx0 amd64 5.4.1-2ubuntu1~14.04 [9,800 B]
Get:12 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libquadmath0 amd64 7.2.0-1ubuntu1~14.04 [132 kB]
Get:13 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libtsan0 amd64 7.2.0-1ubuntu1~14.04 [271 kB]
Get:14 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libubsan0 amd64 7.2.0-1ubuntu1~14.04 [118 kB]
Get:15 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libgcc-5-dev amd64 5.4.1-2ubuntu1~14.04 [2,227 kB]
Get:16 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libstdc++-5-dev amd64 5.4.1-2ubuntu1~14.04 [1,252 kB]
Fetched 4,929 kB in 16s (290 kB/s)
Selecting previously unselected package gcc-7-base:amd64.
(Reading database ... 93696 files and directories currently installed.)
Preparing to unpack .../gcc-7-base_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking gcc-7-base:amd64 (7.2.0-1ubuntu1~14.04) ...
Processing triggers for ccache (3.1.9-1) ...
Updating symlinks in /usr/lib/ccache ...
Setting up gcc-7-base:amd64 (7.2.0-1ubuntu1~14.04) ...
(Reading database ... 93703 files and directories currently installed.)
Preparing to unpack .../libgcc1_1%3a7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libgcc1:amd64 (1:7.2.0-1ubuntu1~14.04) over (1:4.9.3-0ubuntu4) ...
Setting up libgcc1:amd64 (1:7.2.0-1ubuntu1~14.04) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
(Reading database ... 93703 files and directories currently installed.)
Preparing to unpack .../libstdc++6_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libstdc++6:amd64 (7.2.0-1ubuntu1~14.04) over (4.8.4-2ubuntu1~14.04.3) ...
Setting up libstdc++6:amd64 (7.2.0-1ubuntu1~14.04) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
Selecting previously unselected package gcc-5-base:amd64.
(Reading database ... 93704 files and directories currently installed.)
Preparing to unpack .../gcc-5-base_5.4.1-2ubuntu1~14.04_amd64.deb ...
Unpacking gcc-5-base:amd64 (5.4.1-2ubuntu1~14.04) ...
Selecting previously unselected package libasan2:amd64.
Preparing to unpack .../libasan2_5.4.1-2ubuntu1~14.04_amd64.deb ...
Unpacking libasan2:amd64 (5.4.1-2ubuntu1~14.04) ...
Preparing to unpack .../libatomic1_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libatomic1:amd64 (7.2.0-1ubuntu1~14.04) over (4.8.4-2ubuntu1~14.04.3) ...
Selecting previously unselected package libcilkrts5:amd64.
Preparing to unpack .../libcilkrts5_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libcilkrts5:amd64 (7.2.0-1ubuntu1~14.04) ...
Preparing to unpack .../libgomp1_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libgomp1:amd64 (7.2.0-1ubuntu1~14.04) over (4.8.4-2ubuntu1~14.04.3) ...
Preparing to unpack .../libitm1_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libitm1:amd64 (7.2.0-1ubuntu1~14.04) over (4.8.4-2ubuntu1~14.04.3) ...
Selecting previously unselected package liblsan0:amd64.
Preparing to unpack .../liblsan0_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking liblsan0:amd64 (7.2.0-1ubuntu1~14.04) ...
Selecting previously unselected package libmpx0:amd64.
Preparing to unpack .../libmpx0_5.4.1-2ubuntu1~14.04_amd64.deb ...
Unpacking libmpx0:amd64 (5.4.1-2ubuntu1~14.04) ...
Preparing to unpack .../libquadmath0_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libquadmath0:amd64 (7.2.0-1ubuntu1~14.04) over (4.8.4-2ubuntu1~14.04.3) ...
Preparing to unpack .../libtsan0_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libtsan0:amd64 (7.2.0-1ubuntu1~14.04) over (4.8.4-2ubuntu1~14.04.3) ...
Selecting previously unselected package libubsan0:amd64.
Preparing to unpack .../libubsan0_7.2.0-1ubuntu1~14.04_amd64.deb ...
Unpacking libubsan0:amd64 (7.2.0-1ubuntu1~14.04) ...
Selecting previously unselected package libgcc-5-dev:amd64.
Preparing to unpack .../libgcc-5-dev_5.4.1-2ubuntu1~14.04_amd64.deb ...
Unpacking libgcc-5-dev:amd64 (5.4.1-2ubuntu1~14.04) ...
Selecting previously unselected package libstdc++-5-dev:amd64.
Preparing to unpack .../libstdc++-5-dev_5.4.1-2ubuntu1~14.04_amd64.deb ...
Unpacking libstdc++-5-dev:amd64 (5.4.1-2ubuntu1~14.04) ...
Processing triggers for ccache (3.1.9-1) ...
Updating symlinks in /usr/lib/ccache ...
Setting up gcc-5-base:amd64 (5.4.1-2ubuntu1~14.04) ...
Setting up libasan2:amd64 (5.4.1-2ubuntu1~14.04) ...
Setting up libatomic1:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up libcilkrts5:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up libgomp1:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up libitm1:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up liblsan0:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up libmpx0:amd64 (5.4.1-2ubuntu1~14.04) ...
Setting up libquadmath0:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up libtsan0:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up libubsan0:amd64 (7.2.0-1ubuntu1~14.04) ...
Setting up libgcc-5-dev:amd64 (5.4.1-2ubuntu1~14.04) ...
Setting up libstdc++-5-dev:amd64 (5.4.1-2ubuntu1~14.04) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
services
0.02s$ sudo service docker start
start: Job is already running: docker
Setting environment variables from .travis.yml
$ export DIST=juno
$ export PATH=./node_modules/.bin:$PATH
Updating nvm
nvm.install
3.37s$ nvm install lts/*
Downloading and installing node v8.11.1...
Downloading https://nodejs.org/dist/v8.11.1/node-v8.11.1-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v8.11.1 (npm v5.6.0)
cache.1
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.14s$ Installing caching utilities
0.01s
7.30sattempting to download cache archive
fetching master/cache-linux-trusty-4881dc694184bb7ffef9e29dd0604929e98ff7a40ff3b8eb72b3e6cb47e53f0b--node-lts.tgz
found cache
0.01s
3.72sadding /tmp/liftoff to cache
creating directory /tmp/liftoff
$ node --version
v8.11.1
$ npm --version
5.6.0
$ nvm --version
0.33.8
install
36.25s$ npm install @elementaryos/houston
> nodegit@0.20.3 install /home/travis/build/Timecraft/notifier/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install
[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script[Notifier's source code for your convenience](https://github.com/Timecraft/notifier/tree/master)
[nodegit] Success: "/home/travis/build/Timecraft/notifier/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.
> nodegit@0.20.3 postinstall /home/travis/build/Timecraft/notifier/node_modules/nodegit
> node lifecycleScripts/postinstall
npm WARN saveError ENOENT: no such file or directory, open '/home/travis/build/Timecraft/notifier/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/travis/build/Timecraft/notifier/package.json'
npm WARN @fortawesome/vue-fontawesome@0.0.22 requires a peer of vue@^2.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN notifier No description
npm WARN notifier No repository field.
npm WARN notifier No README data
npm WARN notifier No license field.
+ @elementaryos/houston@2.0.0-alpha.29
added 496 packages in 35.612s
373.41s$ houston ci --distribution $DIST
THIS COMMAND IS NOT FULLY COMPLETE
IT ONLY WORKS ON GITHUB WITH TRAVIS AT THIS TIME
Testing "/home/travis/build/Timecraft/notifier" project for "https://github.com/Timecraft/notifier"
....................................
Error while running build for https://github.com/Timecraft/notifier for 0.0.1
================================================================================
  Error: Missing shipped binary at /usr/bin/com.github.Timecraft.notifier
      at FileDebBinary.<anonymous> (/home/travis/build/Timecraft/notifier/node_modules/@elementaryos/houston/dest/worker/task/file/deb/binary.js:38:23)
      at Generator.next (<anonymous>)
      at fulfilled (/home/travis/build/Timecraft/notifier/node_modules/@elementaryos/houston/dest/worker/task/file/deb/binary.js:8:58)
      at <anonymous>
================================================================================
The command "houston ci --distribution $DIST" exited with 1.
cache.2
store build cache
0.01s
2.67snothing changed, not updating cache
Done. Your build exited with 1.
```

[Notifier's source code for your convenience](https://github.com/Timecraft/notifier/tree/master)

**Comment by btkostner** [comment]
Right now, the houston ci process does not change capitalization (might change, still deciding). If you add `--name-appstream com.github.timecraft.notifier` to your travis ci file you should be good.

**Comment by btkostner** [comment]
Woops, that's my bad. It should be `--name-domain com.github.timecraft.notifier` not `--name-appstream`. My bad.

**Comment by btkostner** [comment]
On another note, if you wait about an hour it should no longer be a problem because after talking with the guys we have decided to just lowercase everything.

**Comment by Timecraft** [comment]
If anything, adding the modified part of Code's .travis.yml to my .travis.yml fixed it, so there's always using that solution!

**Comment by btkostner** [comment]
Yeah, Code's `.travis.yml` file sets some names because everything in it uses the `io.elementary.code` namespace instead of `com.github.elementary.code`. Be careful about setting too much in it though because it will not be used when you try to release your project on AppCenter.
