### ISSUE TITLE
  Error: reference 'refs/heads/warning-fixes' not found

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#607]
I dunno what that means :D 

https://travis-ci.org/elementary/code/builds/369746478

```
================================================================================
  Error: reference 'refs/heads/warning-fixes' not found
      at Worker.report (/home/travis/build/elementary/code/node_modules/@elementaryos/houston/dest/worker/worker.js:248:25)
      at Worker.<anonymous> (/home/travis/build/elementary/code/node_modules/@elementaryos/houston/dest/worker/worker.js:179:26)
      at Generator.throw (<anonymous>)
      at rejected (/home/travis/build/elementary/code/node_modules/@elementaryos/houston/dest/worker/worker.js:11:65)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
================================================================================
```

**Comment by btkostner** [comment]
That means houston wasn't able to find the `warning-fixes` branch with git.

**Comment by danrabbit** [comment]
Hrm this seems to be happening for multiple branches of Code even though those branches do exist

**Comment by btkostner** [comment]
This might be related to travis then. Running it locally:

```
btkostner@Caprica:~/Projects/elementary/code$ houston ci --type system-app --name-appstream io.elementary.code.desktop --name-domain io.elementary.code --name-human Code --distribution juno --repo https://github.com/elementary/code
THIS COMMAND IS NOT FULLY COMPLETE
IT ONLY WORKS ON GITHUB WITH TRAVIS AT THIS TIME
Testing "/home/btkostner/Projects/elementary/code" project for "https://github.com/elementary/code"
......................................
Built https://github.com/elementary/code for version 0.0.1

================================================================================

  AppCenter ran a bunch of tests on your appstream file. These are the results.
  
  
  ## Warnings:
  Most of these are fixed during the building process, but you should ensure they
  are fixed in your code for future releases.
    - "id" field should be "io.elementary.code.desktop"
  
  ### For more information, see:
  - [The AppStream Quickstart Guide](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html)
  - [The AppStream Metadata Specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html)

================================================================================
```
