### ISSUE TITLE
Houston CI: Internal error while running

### ISSUE THREAD

**Issue by cjfloss** [elementary/houston#675]
```Error while running build for https://github.com/cjfloss/envelope for 0.0.1
================================================================================
# Internal error while running
Cannot copy '../nopt/bin/nopt.js' to a subdirectory of itself, '../nopt/bin/nopt.js'.
Error: Cannot copy '../nopt/bin/nopt.js' to a subdirectory of itself, '../nopt/bin/nopt.js'.
    at fs.readlink (/home/travis/build/cjfloss/envelope/node_modules/fs-extra/lib/copy/copy.js:190:21)
    at FSReqWrap.oncomplete (fs.js:141:20)
================================================================================
```

**Comment by btkostner** [comment]
Update your `travis.yml` file from [the wiki](https://github.com/elementary/houston/wiki/Continuous-Integration#standard-travisyml).

Specifically, the install line should be:
```
  - npm i -g @elementaryos/houston
```
