### ISSUE TITLE
Houston CI builds are failing

### ISSUE THREAD

**Issue by RyanAfrish7** [elementary/houston#742]
The .travis.yml file used is same as the one in wiki page.

```
# Internal error while running
Cannot copy '../semver/bin/semver' to a subdirectory of itself, '../semver/bin/semver'.
Error: Cannot copy '../semver/bin/semver' to a subdirectory of itself, '../semver/bin/semver'.
    at fs.readlink (/home/travis/build/RyanAfrish7/satellite/node_modules/fs-extra/lib/copy/copy.js:190:21)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by ztefn** [comment]
Just got the exact same error for Houston CI when trying to test the [elementary branch](/ztefn/haguichi/tree/elementary) of Haguichi: https://travis-ci.com/ztefn/haguichi/jobs/254639701

```
# Internal error while running

Cannot copy 'haguichi-disconnected.svg' to a subdirectory of itself, 'haguichi-disconnected.svg'.
Error: Cannot copy 'haguichi-disconnected.svg' to a subdirectory of itself, 'haguichi-disconnected.svg'.
    at fs.readlink (/home/travis/.nvm/versions/node/v10.17.0/lib/node_modules/@elementaryos/houston/node_modules/fs-extra/lib/copy/copy.js:190:21)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```
