### ISSUE TITLE
Incorrect desktop file icon value     at DesktopIcon.<anonymous>

### ISSUE THREAD

**Issue by miguelsotobaez** [elementary/houston#747]
Hi, when i run the travis ci i get this error:

# Incorrect desktop file icon value
Log: Incorrect desktop file icon value
    at DesktopIcon.<anonymous> (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:109:35)
    at step (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:49:23)
    at Object.next (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:30:53)
    at fulfilled (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:21:58)

Do you know how to fix it?

Thanks

**Comment by btkostner** [comment]
This means that your `Icon=` in your desktop is not correct. It should be RDNN format. What repository is this for?

**Comment by miguelsotobaez** [comment]
Ooh thanks, i'm new in elementary os and gtk, the repository is https://github.com/duocoder/zygardex, I started today with this and i'm trying to work with the travis ci from your get started documentation.

At the moment only for testing purposes.

Regards

**Comment by miguelsotobaez** [comment]
@btkostner  Sorry to bother you but I still have problems with Travis CI, I changed the name of the icon and I still get the error message.

```
# Incorrect desktop file icon value
Log: Incorrect desktop file icon value
    at DesktopIcon.<anonymous> (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:109:35)
    at step (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:49:23)
    at Object.next (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:30:53)
    at fulfilled (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/dest/worker/task/desktop/icon.js:21:58)
```


The configuration of my file is as follows com.github.duocoder.zygardex.desktop.in:

```
[Desktop Entry]
Name=Zygardex
GenericName=Zygardex Pokemon Database
Comment=See and analyze all pokemon
Categories=Utility;Education;
Exec="com.github.duocoder.zygardex"
Icon=com.github.duocoder.zygardex.png
Terminal=false
Type=Application
Keywords=Zygardex;Pokemon;Database;
```

First time I listen to the RDNN format If you could explain me a bit what it is, I would appreciate it very much.

My repository is: https://github.com/duocoder/zygardex/

**Comment by btkostner** [comment]
@miguelsotobaez You don't need the `.png` part. https://github.com/danrabbit/nimbus/blob/master/data/com.github.danrabbit.nimbus.desktop.in#L5

**Comment by miguelsotobaez** [comment]
> @miguelsotobaez You don't need the `.png` part. https://github.com/danrabbit/nimbus/blob/master/data/com.github.danrabbit.nimbus.desktop.in#L5

@btkostner I had to thank you, this solution solve the problem to me, now the Travis CI is now complete!

Regards.
