### ISSUE TITLE
Travis CI app builds failing:- No such image: houston-extract-deb:latest

### ISSUE THREAD

**Issue by ianmjones** [elementary/houston#751]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug

The normal Travis CI builds for apps are currently failing due to the following error being emitted from the @elementaryos/houston npm package.

`No such image: houston-extract-deb:latest`

See Logs section below.

### Logs

Full example Travis CI build log here: https://travis-ci.com/bytepixie/snippetpixie/builds/131685378

Relevant snippet:

```
$ npm i -g @elementaryos/houston

597.87s$ houston ci --distribution $DIST --name-domain com.github.bytepixie.snippetpixie

THIS COMMAND IS NOT FULLY COMPLETE

IT ONLY WORKS ON GITHUB WITH TRAVIS AT THIS TIME

Testing "/home/travis/build/bytepixie/snippetpixie" project for "https://github.com/bytepixie/snippetpixie"

............................................................

Error while running build for https://github.com/bytepixie/snippetpixie for 0.0.1

================================================================================

# Internal error while running

(HTTP code 404) no such container - No such image: houston-extract-deb:latest 

Error: (HTTP code 404) no such container - No such image: houston-extract-deb:latest 

    at /home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/node_modules/docker-modem/lib/modem.js:257:17

    at getCause (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/node_modules/docker-modem/lib/modem.js:287:7)

    at Modem.buildPayload (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/node_modules/docker-modem/lib/modem.js:256:5)

    at IncomingMessage.<anonymous> (/home/travis/.nvm/versions/node/v10.16.3/lib/node_modules/@elementaryos/houston/node_modules/docker-modem/lib/modem.js:232:14)

    at IncomingMessage.emit (events.js:203:15)

    at endReadableNT (_stream_readable.js:1145:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

================================================================================
```

## Platform Information

Travis CI (as per wiki example) triggered by feature branch push of app code.

.travis-ci.yml file used in example: https://github.com/bytepixie/snippetpixie/blob/develop/.travis.yml

**Comment by cassidyjames** [comment]
I'm also getting this on Ephemeral. https://travis-ci.com/cassidyjames/ephemeral

**Comment by ianmjones** [comment]
Looking good for me too. Thanks @gamerlv for the fix and @btkostner for the review and merge.
